import { Listing } from "./types";

// Realistic mock listings across North County San Diego
// Cities: Carlsbad, Encinitas, Oceanside, Vista, San Marcos
export const MOCK_LISTINGS: Listing[] = [
  // Carlsbad listings
  {
    id: "1",
    produceName: "Meyer Lemons",
    produceType: "fruit",
    description: "Beautiful Meyer lemons from my backyard tree. Sweet and less acidic than regular lemons - perfect for cooking or lemonade. Tree is overflowing this season!",
    growerName: "Maria G.",
    neighborhood: "Carlsbad",
    latitude: 33.1581,
    longitude: -117.3506,
    availability: "now",
    pickupInstructions: "On the porch at 123 Elm St. Help yourself to a bag, just text me when you're coming by.",
    contactMethod: "phone",
    contactPhone: "(760) 555-0101",
    photoUrl: "https://images.unsplash.com/photo-1590502593747-42a996133562?w=800&q=80",
    createdAt: "2026-02-08T10:00:00Z",
  },
  {
    id: "2",
    produceName: "Hass Avocados",
    produceType: "fruit",
    description: "Creamy Hass avocados ready to pick. Some are ripe now, others will be ready in a few days. About 20 available.",
    growerName: "Carlos R.",
    neighborhood: "Carlsbad",
    latitude: 33.1425,
    longitude: -117.3280,
    availability: "now",
    pickupInstructions: "Ring the doorbell and I'll bring them out. Cash tip jar if you'd like but not required!",
    contactMethod: "both",
    contactPhone: "(760) 555-0102",
    contactEmail: "carlos.r@email.com",
    photoUrl: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800&q=80",
    createdAt: "2026-02-07T14:30:00Z",
  },
  {
    id: "3",
    produceName: "Fresh Zucchini",
    produceType: "vegetables",
    description: "Organic zucchini from my raised beds. Various sizes available. Great for grilling, baking, or spiralizing!",
    growerName: "Jennifer L.",
    neighborhood: "Carlsbad",
    latitude: 33.1289,
    longitude: -117.2958,
    availability: "now",
    pickupInstructions: "Come to the side gate and grab what you need from the basket. Leave a note so I know who stopped by!",
    contactMethod: "email",
    contactEmail: "jen.garden@email.com",
    photoUrl: "https://images.unsplash.com/photo-1563252722-6434563a985d?w=800&q=80",
    createdAt: "2026-02-09T08:15:00Z",
  },

  // Encinitas listings
  {
    id: "4",
    produceName: "Cherry Tomatoes",
    produceType: "vegetables",
    description: "Sun Gold and Sweet 100 cherry tomatoes. Incredibly sweet! Pick your own from the vine or take a pre-filled basket.",
    growerName: "David K.",
    neighborhood: "Encinitas",
    latitude: 33.0370,
    longitude: -117.2920,
    availability: "now",
    pickupInstructions: "Backyard garden - come through the side gate (code: 1234). Baskets and bags provided.",
    contactMethod: "phone",
    contactPhone: "(760) 555-0104",
    photoUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&q=80",
    createdAt: "2026-02-06T16:00:00Z",
  },
  {
    id: "5",
    produceName: "Fresh Basil & Mint",
    produceType: "herbs",
    description: "Genovese basil and spearmint growing like crazy. Take as much as you need - I have way more than I can use!",
    growerName: "Sarah M.",
    neighborhood: "Encinitas",
    latitude: 33.0492,
    longitude: -117.2615,
    availability: "now",
    pickupInstructions: "Herbs are in pots on the front porch. Bring scissors or I have some you can borrow.",
    contactMethod: "email",
    contactEmail: "sarah.herbs@email.com",
    photoUrl: "https://images.unsplash.com/photo-1618164436241-4473940d1f5c?w=800&q=80",
    createdAt: "2026-02-08T11:30:00Z",
  },
  {
    id: "6",
    produceName: "Passion Fruit",
    produceType: "fruit",
    description: "Purple passion fruit from our prolific vine. Amazing in smoothies, desserts, or just eat them fresh. About 30 available.",
    growerName: "Linda W.",
    neighborhood: "Encinitas",
    latitude: 33.0558,
    longitude: -117.2780,
    availability: "now",
    pickupInstructions: "Text me and I'll leave them in a cooler on the porch. Usually home on weekends.",
    contactMethod: "phone",
    contactPhone: "(760) 555-0106",
    photoUrl: "https://images.unsplash.com/photo-1604495772376-9657f0035eb5?w=800&q=80",
    createdAt: "2026-02-05T09:00:00Z",
  },

  // Oceanside listings
  {
    id: "7",
    produceName: "Farm Fresh Eggs",
    produceType: "eggs",
    description: "Free-range eggs from my happy backyard chickens. Mix of brown and blue eggs. Fed organic feed and garden scraps.",
    growerName: "Robert T.",
    neighborhood: "Oceanside",
    latitude: 33.1959,
    longitude: -117.3795,
    availability: "now",
    availabilityDetails: "New eggs every morning",
    pickupInstructions: "Egg fridge is by the garage. Take a carton and leave $5 in the jar if you can, but free is fine too.",
    contactMethod: "phone",
    contactPhone: "(760) 555-0107",
    photoUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=800&q=80",
    createdAt: "2026-02-09T06:00:00Z",
  },
  {
    id: "8",
    produceName: "Valencia Oranges",
    produceType: "fruit",
    description: "Juicy Valencia oranges - perfect for fresh juice. Tree is loaded! Come pick your own or I can bag some up.",
    growerName: "Mike P.",
    neighborhood: "Oceanside",
    latitude: 33.2120,
    longitude: -117.3250,
    availability: "now",
    pickupInstructions: "Orange tree is in the front yard. Feel free to pick anytime. Bring a bag!",
    contactMethod: "both",
    contactPhone: "(760) 555-0108",
    contactEmail: "mike.oranges@email.com",
    photoUrl: "https://images.unsplash.com/photo-1547514701-42782101795e?w=800&q=80",
    createdAt: "2026-02-04T13:00:00Z",
  },
  {
    id: "9",
    produceName: "Japanese Cucumbers",
    produceType: "vegetables",
    description: "Crispy Japanese cucumbers. Less bitter and seedless. Great for salads, pickling, or snacking.",
    growerName: "Yuki H.",
    neighborhood: "Oceanside",
    latitude: 33.1850,
    longitude: -117.3420,
    availability: "now",
    pickupInstructions: "Available Saturday mornings 8am-11am. Ring doorbell and I'll bring them out fresh.",
    contactMethod: "email",
    contactEmail: "yuki.garden@email.com",
    photoUrl: "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=800&q=80",
    createdAt: "2026-02-08T07:45:00Z",
  },

  // Vista listings
  {
    id: "10",
    produceName: "Rosemary & Thyme",
    produceType: "herbs",
    description: "Established rosemary and thyme plants producing more than we can ever use. Great for cooking or drying.",
    growerName: "Patricia N.",
    neighborhood: "Vista",
    latitude: 33.2000,
    longitude: -117.2426,
    availability: "now",
    pickupInstructions: "Herb garden is on the side of the house. Help yourself anytime!",
    contactMethod: "phone",
    contactPhone: "(760) 555-0110",
    photoUrl: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=800&q=80",
    createdAt: "2026-02-07T10:30:00Z",
  },
  {
    id: "11",
    produceName: "Fuji Apples",
    produceType: "fruit",
    description: "Sweet Fuji apples from our small orchard. Some have minor blemishes but taste amazing. Great for eating fresh or baking.",
    growerName: "Tom S.",
    neighborhood: "Vista",
    latitude: 33.2180,
    longitude: -117.2285,
    availability: "upcoming",
    availabilityDetails: "Ready next weekend (Feb 15-16)",
    pickupInstructions: "Will post exact pickup times closer to the date. Planning Saturday morning.",
    contactMethod: "email",
    contactEmail: "tom.orchard@email.com",
    photoUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=800&q=80",
    createdAt: "2026-02-09T15:00:00Z",
  },
  {
    id: "12",
    produceName: "Bell Peppers",
    produceType: "vegetables",
    description: "Red, yellow, and green bell peppers. Organic, no pesticides. Perfect for stuffing, salads, or stir-fry.",
    growerName: "Angela C.",
    neighborhood: "Vista",
    latitude: 33.1890,
    longitude: -117.2580,
    availability: "now",
    pickupInstructions: "Peppers are in a basket by the mailbox. First come, first served. I restock daily.",
    contactMethod: "phone",
    contactPhone: "(760) 555-0112",
    photoUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=800&q=80",
    createdAt: "2026-02-06T08:00:00Z",
  },
  {
    id: "13",
    produceName: "Duck Eggs",
    produceType: "eggs",
    description: "Rich, creamy duck eggs. Larger than chicken eggs with more protein. Amazing for baking!",
    growerName: "Nancy B.",
    neighborhood: "Vista",
    latitude: 33.2075,
    longitude: -117.2150,
    availability: "now",
    availabilityDetails: "Wednesdays and Saturdays",
    pickupInstructions: "Text to reserve eggs. I collect fresh on Wed/Sat mornings.",
    contactMethod: "phone",
    contactPhone: "(760) 555-0113",
    photoUrl: "https://images.unsplash.com/photo-1498654077810-12c21d4d6dc3?w=800&q=80",
    createdAt: "2026-02-08T09:30:00Z",
  },

  // San Marcos listings
  {
    id: "14",
    produceName: "Grapefruit",
    produceType: "fruit",
    description: "Ruby Red grapefruit from our 30-year-old tree. Sweet and tangy. Tree produces hundreds every year!",
    growerName: "George M.",
    neighborhood: "San Marcos",
    latitude: 33.1434,
    longitude: -117.1661,
    availability: "now",
    pickupInstructions: "Grapefruit box is at the end of the driveway. Take what you need!",
    contactMethod: "both",
    contactPhone: "(760) 555-0114",
    contactEmail: "george.citrus@email.com",
    photoUrl: "https://images.unsplash.com/photo-1577234286642-fc512a5f8f11?w=800&q=80",
    createdAt: "2026-02-05T11:00:00Z",
  },
  {
    id: "15",
    produceName: "Swiss Chard",
    produceType: "vegetables",
    description: "Rainbow Swiss chard - beautiful and nutritious. Cut-and-come-again variety so there's always more.",
    growerName: "Helen R.",
    neighborhood: "San Marcos",
    latitude: 33.1250,
    longitude: -117.1820,
    availability: "now",
    pickupInstructions: "Garden is in the backyard. Come through side gate and harvest what you need. Scissors provided.",
    contactMethod: "email",
    contactEmail: "helen.veggies@email.com",
    photoUrl: "https://images.unsplash.com/photo-1490914327627-9fe8d52f4d90?w=800&q=80",
    createdAt: "2026-02-07T14:00:00Z",
  },
  {
    id: "16",
    produceName: "Kumquats",
    produceType: "fruit",
    description: "Tiny kumquats you eat whole - skin and all! Sweet skin, tart inside. Kids love them. Tree is overloaded.",
    growerName: "Betty J.",
    neighborhood: "San Marcos",
    latitude: 33.1380,
    longitude: -117.2050,
    availability: "now",
    pickupInstructions: "Kumquat tree is in the front yard by the fence. Pick as many as you want!",
    contactMethod: "phone",
    contactPhone: "(760) 555-0116",
    photoUrl: "https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=800&q=80",
    createdAt: "2026-02-09T10:15:00Z",
  },
  {
    id: "17",
    produceName: "Jalapeños & Serranos",
    produceType: "vegetables",
    description: "Hot peppers for salsa lovers! Jalapeños are medium heat, serranos are spicier. Also have some mild Anaheims.",
    growerName: "Ricardo F.",
    neighborhood: "San Marcos",
    latitude: 33.1520,
    longitude: -117.1450,
    availability: "now",
    pickupInstructions: "Peppers are by the front door in labeled bags by heat level. Ring bell if you want to chat!",
    contactMethod: "phone",
    contactPhone: "(760) 555-0117",
    photoUrl: "https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=800&q=80",
    createdAt: "2026-02-08T16:30:00Z",
  },
  {
    id: "18",
    produceName: "Honey (Local Raw)",
    produceType: "other",
    description: "Raw wildflower honey from my backyard beehives. Great for allergies! Small jars available.",
    growerName: "Steve K.",
    neighborhood: "San Marcos",
    latitude: 33.1605,
    longitude: -117.1280,
    availability: "upcoming",
    availabilityDetails: "Next harvest mid-February",
    pickupInstructions: "Email to get on the list for the next harvest.",
    contactMethod: "email",
    contactEmail: "steve.bees@email.com",
    photoUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&q=80",
    createdAt: "2026-02-09T12:00:00Z",
  },
];

// Helper to calculate distance between two points (Haversine formula)
export function calculateDistance(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const R = 3959; // Earth's radius in miles
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

// Format distance for display
export function formatDistance(miles: number): string {
  if (miles < 0.1) return "< 0.1 mi";
  return `${miles.toFixed(1)} mi`;
}
